[package]
name = "rust-interface"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
godot = { path = "../../gdext-master/godot"}
audio-processor = { path = "../../audio-processor"}
hound = "3.5.1"
crevice = "0.18.0" 

[profile.dev]
opt-level = 0
