#version 460
#include "imports/utils.comp"

layout(local_size_x = 64) in;


layout(constant_id = 0) const uint WINDOW_SIZE = 1024;
layout(constant_id = 1) const uint FRAME_SIZE = 512;
layout(constant_id = 2) const uint DELAY_BUFFER_SIZE = 220160; // in samples (= ~5s @ 44100Hz, rounded to %WINDOW_SIZE)
layout(constant_id = 3) const float SAMPLING_RATE = 44100;

const float SOUND_SPEED = 340.29;

// max delay in samples is: buf size - cpu pipeline (can't read where its being uploaded) - window size (the whole window needs to be valid)
const uint MAX_DELAY = DELAY_BUFFER_SIZE - (FRAME_SIZE) - WINDOW_SIZE;
const uint INITIAL_OFFSET = -(WINDOW_SIZE - FRAME_SIZE) + DELAY_BUFFER_SIZE; // start WINDOW_SIZE - FRAME_SIZE before 0 (wraps around adding BUFFER_SIZE)


layout(push_constant, std430) uniform Camera {
    vec3 position;
    uint frame_idx;
} camera;

layout(binding = 0, std430) readonly restrict buffer AudioInstances {
    Instance instances[];
};

layout(binding = 1, std430) readonly restrict buffer DelayBuffer {
    vec2 samples[];
};

layout(binding = 2, std430) writeonly restrict buffer FftInput {
    vec2 fft_input[];
};


uint delayed_index(float dist, uint instance_idx) {
    // if there's no delay, we can start at: initial offset shifted ahead by how many frames have passed
    uint zero_delay_start_idx = camera.frame_idx * FRAME_SIZE + INITIAL_OFFSET; // no % DELAY_BUFFER_SIZE because it's handled later
    float delay = dist / SOUND_SPEED;

    uint samples_delay = uint(delay / (float(FRAME_SIZE) / SAMPLING_RATE));
    uint clamped_delay = uint(min(samples_delay, MAX_DELAY));

    // the start value is: zero delay idx - delay % buffer size. Buffer size is added to avoid negatives.
    uint start_idx = zero_delay_start_idx + DELAY_BUFFER_SIZE - clamped_delay;

    return (start_idx + gl_GlobalInvocationID.x) % DELAY_BUFFER_SIZE + instance_idx * DELAY_BUFFER_SIZE;
}

// width of dispatch MUST BE == WINDOW_SIZE
// height of dispatch is given by instance count
void main() {
    Instance instance = instances[gl_GlobalInvocationID.y];
    vec3 relative_position = instance.position - camera.position;
    float total_dist = length(relative_position) + instance.additional_dist;

    uint sample_idx = delayed_index(total_dist, instance.index);
    uint fft_idx = gl_GlobalInvocationID.y * WINDOW_SIZE + gl_GlobalInvocationID.x;
    fft_input[fft_idx] = samples[sample_idx];
}
