#version 460
#extension GL_EXT_shader_atomic_float : enable  // atomics for floats
#extension GL_KHR_shader_subgroup_arithmetic : enable // subgroup arithmetic
#include "imports/utils.comp"

// x = frequency, y = source
layout(local_size_x = 1, local_size_y = 64, local_size_z = 1) in;


layout(constant_id = 0) const uint WINDOW_SIZE = 1024;
layout(constant_id = 1) const uint FRAME_SIZE = 512;
layout(constant_id = 2) const uint FILTER_SIZE = 1024;
layout(constant_id = 3) const float SAMPLING_RATE = 44100;
layout(constant_id = 4) const float MIN_ELEVATION = M_PI;
layout(constant_id = 5) const float MAX_ELEVATION = 0;

const uint SINUSOIDAL_PERIODS = WINDOW_SIZE / (2 * FRAME_SIZE);

layout(push_constant, std430) uniform PushConstants {
    mat3 prev_rotation;
    mat3 next_rotation;
    vec3 position;
    uint instance_amount;
    uint output_select;
};

layout(binding = 0, std430) readonly restrict buffer AudioInstances {
    Instance instances[];
};

layout(binding = 1, std430) readonly restrict buffer FftOutput {
    vec2 samples[];
};

layout(binding = 2, std430) coherent restrict buffer OutputLeft {
    ivec2 samples[];
} left_output[2];

layout(binding = 3, std430) coherent restrict buffer OutputRight {
    ivec2 samples[];
} right_output[2];

layout(binding = 4) uniform sampler3D hrtfLeft;
layout(binding = 5) uniform sampler3D hrtfRight;

// todo: use something more compact than floats for this as we don't really need more than 16 bits of precision
layout(binding = 6, std430) restrict buffer Loudness {
    float loudness[];
} loudness_buf[2];


vec2 decode_polar_filter(vec3 polar) {
    vec2 normalized = normalize(polar.yz);
    return vec2(normalized.x * polar.x, normalized.y * polar.x);
}

vec2 cartesian_to_tex_coords(vec3 coords) {
    float radius = length(coords);
    float elevation = acos(coords.y / radius);
    float azimuth = atan(-coords.z, coords.x);
    if (azimuth < 0) {
        azimuth = azimuth + 2 * M_PI;
    }

    return vec2(
        // here we want the range of elevations between max and min to be stretched to 0 and 1,
        // and everything else to fall outside
        elevation / (MIN_ELEVATION - MAX_ELEVATION) - MAX_ELEVATION,
        azimuth / (2.0 * M_PI)
    );
}

vec2 complex_mult(vec2 a, vec2 b) {
    return mat2(a.x, a.y, -a.y, a.x) * b;
}

// todo: improve math here and above to be more physically-based
float squared_len(vec2 val) {
    return val.x * val.x + val.y * val.y;
}

// Represents how many dB full amplitude is equivalent to in the virtual world
const float FULL_VOLUME = 80.0;
const float PEAK_FREQUENCY = log(2000); // 2000 Hz is used as peak frequency for the curve

float inverse_square_attenuation(float dist) {
    // I (intensity) = P / (4 pi r^2)
    // P ≈ Amplitude^2
    // I = k*A^2 / (4 pi r^2)
    // to keep the same intensity, doubling R requires doubling A -> A is proportional to 1 / r (better math on the notes)
    const float CONSTANT = 7.0;
    // an amplitude multiplication of 0.00002 is more or less equivalent to -96dB, considered by many to be absolute quiet
    return clamp(CONSTANT / dist, 0.00002, 2.0);
}

void save_loudness(vec2 Xk, uint instance_idx, uint sample_idx) {
    // Rough approximation of equal-loudness countour curve using a quadratic equation
    float frequency = float(sample_idx) / WINDOW_SIZE * SAMPLING_RATE;
    float reduction = pow(log(frequency) - PEAK_FREQUENCY, 2.0);

    // Calculate decibels. Full amplitude = -0dB + FULL_VOLUME
    float sq_ampl = squared_len(max(Xk, 0.00002));
    float decibels = 10 * log(sq_ampl) / log(10) + FULL_VOLUME - reduction;

    loudness_buf[output_select].loudness[instance_idx * WINDOW_SIZE + sample_idx] = decibels;
}

void circular_samples(uint sample_idx, uint fft_offset, out vec2 prev, out vec2 curr, out vec2 next) {
    prev = samples[(sample_idx - SINUSOIDAL_PERIODS + WINDOW_SIZE) % WINDOW_SIZE + fft_offset];
    curr = samples[sample_idx + fft_offset];
    next = samples[(sample_idx + SINUSOIDAL_PERIODS) % WINDOW_SIZE + fft_offset];
}

void main() {
    uint sample_idx = gl_GlobalInvocationID.x;
    uint instance_idx = gl_GlobalInvocationID.y;

    if (instance_idx >= instance_amount) return;

    Instance instance = instances[instance_idx];
    vec3 relative_position = instance.position - position;
    vec3 prev_direction = prev_rotation * relative_position;
    vec3 next_direction = next_rotation * relative_position;

    float dist = length(relative_position) + instance.additional_dist;
    uint fft_offset = instance_idx * WINDOW_SIZE;

    // Normalized coordinates
    float x_coord = float(sample_idx) / FILTER_SIZE;
    vec3 prev_hrtf_tex_coord = vec3(x_coord, cartesian_to_tex_coords(prev_direction));
    vec3 next_hrtf_tex_coord = vec3(x_coord, cartesian_to_tex_coords(next_direction));

    // HRTF samples
    vec2 prev_left_hrtf = decode_polar_filter(texture(hrtfLeft, prev_hrtf_tex_coord).xyz);
    vec2 prev_right_hrtf = decode_polar_filter(texture(hrtfRight, prev_hrtf_tex_coord).xyz);
    vec2 next_left_hrtf = decode_polar_filter(texture(hrtfLeft, next_hrtf_tex_coord).xyz);
    vec2 next_right_hrtf = decode_polar_filter(texture(hrtfRight, next_hrtf_tex_coord).xyz);

    float attenuation = inverse_square_attenuation(dist) * instance.attenuation;

    // Load samples from FFT output
    vec2 Xk_P, Xk, XkP;
    circular_samples(sample_idx, fft_offset, Xk_P, Xk, XkP);
    save_loudness(Xk * attenuation, instance_idx, sample_idx);

    // Apply lerp curve
    vec2 prev_Xk = (-0.5 * Xk_P + Xk + -0.5 * XkP) * attenuation;
    vec2 next_Xk = (0.5 * Xk_P + Xk + 0.5 * XkP) * attenuation;

    // Sum the two lerped versions
    vec2 attenuated_left = complex_mult(prev_Xk, prev_left_hrtf) + complex_mult(next_Xk, next_left_hrtf);
    vec2 attenuated_right = complex_mult(prev_Xk, prev_right_hrtf) + complex_mult(next_Xk, next_right_hrtf);

    const float I16_MAX = 32767.0;
    barrier();
    ivec2 subgroup_left_sum = ivec2(subgroupAdd(attenuated_left) * I16_MAX);
    ivec2 subgroup_right_sum = ivec2(subgroupAdd(attenuated_right) * I16_MAX);

    if (subgroupElect()) {
        atomicAdd(left_output[output_select].samples[sample_idx].x, subgroup_left_sum.x);
        atomicAdd(left_output[output_select].samples[sample_idx].y, subgroup_left_sum.y);
        atomicAdd(right_output[output_select].samples[sample_idx].x, subgroup_right_sum.x);
        atomicAdd(right_output[output_select].samples[sample_idx].y, subgroup_right_sum.y);

        if (sample_idx != 0 && sample_idx != WINDOW_SIZE / 2) {
            uint idx = WINDOW_SIZE - sample_idx;
            atomicAdd(left_output[output_select].samples[idx].x, subgroup_left_sum.x);
            atomicAdd(left_output[output_select].samples[idx].y, -subgroup_left_sum.y);
            atomicAdd(right_output[output_select].samples[idx].x, subgroup_right_sum.x);
            atomicAdd(right_output[output_select].samples[idx].y, -subgroup_right_sum.y);
        }
    }
}