#version 460
#extension GL_EXT_shader_atomic_float : enable  // atomics for floats
#extension GL_KHR_shader_subgroup_arithmetic : enable // subgroup arithmetic
#include "imports/utils.comp"

// x = frequency, y = source
layout(local_size_x = 1, local_size_y = 64, local_size_z = 1) in;


layout(constant_id = 0) const uint WINDOW_SIZE = 1024;
layout(constant_id = 1) const uint FRAME_SIZE = 512;
layout(constant_id = 2) const uint FILTER_SIZE = 1024;

layout(constant_id = 5) const float SAMPLING_RATE = 44100;

layout(constant_id = 6) const float MIN_ELEVATION = M_PI;
layout(constant_id = 7) const float MAX_ELEVATION = 0;


layout(push_constant, std430) uniform PushConstants {
    uint instance_amount;
};

layout(binding = 0, std430) readonly restrict buffer AudioInstances {
    Instance instances[];
};

layout(binding = 1, std430) readonly restrict buffer FftOutput {
    vec2 samples[];
};

layout(binding = 2, std430) restrict buffer OutputLeft {
    vec2 leftOutput[];
};

layout(binding = 3, std430) restrict buffer OutputRight {
    vec2 rightOutput[];
};

layout(binding = 4) uniform sampler3D hrtfLeft;
layout(binding = 5) uniform sampler3D hrtfRight;

// todo: log
vec2 decode_polar_filter(vec3 polar) {
    vec2 normalized = normalize(polar.yz);
    return vec2(normalized.x * polar.x, normalized.y * polar.x);
}

vec2 cartesian_to_tex_coords(vec3 coords) {
    float radius = length(coords);
    float elevation = acos(coords.y / radius);
    float azimuth = atan(-coords.z, coords.x);
    if (azimuth < 0) {
        azimuth = azimuth + 2 * M_PI;
    }

    return vec2(
        // here we want the range of elevations between max and min to be stretched to 0 and 1,
        // and everything else to fall outside
        elevation / (MIN_ELEVATION - MAX_ELEVATION) - MAX_ELEVATION,
        azimuth / (2.0 * M_PI)
    );
}

vec2 complex_mult(vec2 a, vec2 b) {
    return mat2(a.x, a.y, -a.y, a.x) * b;
}

float attenuation(float f, float dist) {
    const float T_REF = 293.15;
    const float T = T_REF;
    const float T_ZERO = 273.16;
    const float RH = 0.5; // 50% relative humidity!

    const float P_SAT = pow(10, -6.8346 * pow(T_ZERO / T, 1.261) + 4.6151);
    const float H = RH * P_SAT;

    const float F_RO = 24.0 + 40400.0 * H * (0.02 + H) / (0.391 + H);
    const float F_RN = pow(T_REF / T, 0.5) * (9 + 280.0 * H * exp(-4.17 * (pow(T_REF / T, 1.0 / 3.0) - 1)));

    float f2 = f * f;
    float alpha = f2 * (1.84 * pow(10, -11) * pow(T / T_REF, 0.5)
                         + pow(T / T_REF, -2.5) * (0.01278 * exp(-2239.1 / T) / (F_RO + f2 / F_RO))
                                                   + 0.1068 * exp(-3352.0 / T) / (F_RN + f2 / F_RN));

    return exp(-alpha * dist);
}

void main() {
    // todo: research the following for performance:
    // - coherent buffer access (better split or single buffer?)
    // - coherent buffer access (better in warp or across warps?)
    // - frames access (better continuous in invocation, or split throughout warp?)
    // - caching?
    
    // todo: experiment with summing local memory first and then only writing here if you the last thread; it should be MUCH fastr.
    //  basically, all the threads must write their output to local memory and then barrier. after the barrier, one thread can do the sum and write it
    //  and the rest can just "terminate"; or use subgroupAdd() (subgroups should be vertical slices in that case)

    uint sample_idx = gl_GlobalInvocationID.x;
    uint instance_idx = gl_GlobalInvocationID.y;
    
    if (instance_idx >= instance_amount) return;
    
    Instance instance = instances[instance_idx];
    float dist = length(instance.direction);
    uint fft_offset = instance_idx * WINDOW_SIZE;

    // Normalized coordinates
    vec3 hrtf_tex_coord = vec3(
        float(sample_idx) / FILTER_SIZE,
        cartesian_to_tex_coords(instance.direction)
    );

    vec2 left_hrtf = decode_polar_filter(texture(hrtfLeft, hrtf_tex_coord).xyz);
    vec2 right_hrtf = decode_polar_filter(texture(hrtfRight, hrtf_tex_coord).xyz);
    
    vec2 Xk = vec2(samples[sample_idx + fft_offset]);
//    float frequency = float(idx) / WINDOW_SIZE * SAMPLING_RATE;
//    Xk *= attenuation(frequency, dist);

    vec2 attenuated_left = complex_mult(Xk, left_hrtf);
    vec2 attenuated_right = complex_mult(Xk, right_hrtf);

    // todo: for now we only support up to 64 (AMD) and 32 (NVIDIA) audio sources! Work around this!
    vec2 subgroup_left_sum = subgroupAdd(attenuated_left);
    vec2 subgroup_right_sum = subgroupAdd(attenuated_right);

    if (subgroupElect()) {
        leftOutput[sample_idx] += subgroup_left_sum;
        rightOutput[sample_idx] += subgroup_right_sum;

        if (sample_idx != 0 && sample_idx != WINDOW_SIZE / 2) {
            uint idx = WINDOW_SIZE - sample_idx;
            leftOutput[idx] += vec2(subgroup_left_sum.x, -subgroup_left_sum.y);
            rightOutput[idx] += vec2(subgroup_right_sum.x, -subgroup_right_sum.y);
        }
    }
}