#version 460

layout(constant_id = 0) const uint POINT_AMOUNT = 1024;
layout(constant_id = 1) const uint SOURCE_AMOUNT = 1;
layout(constant_id = 4) const uint KMEANS_CENTROIDS = 8;

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct Output {
    vec3 location;
    float total_distance;
    uint bounces;
    uint source;
    bool found_source;
};

layout(binding = 0, std430) readonly buffer RtOutputBuffer {
    vec3 output_camera_pos; // used for reprojection
    Output outputs[];
};

layout(binding = 1) readonly restrict buffer KMeansCentroids {
    vec3 centroids[];
};

layout(binding = 2) writeonly restrict buffer KMeansNeighbours {
    int neighbours[];
};

// Dispatch size: X = POINT_AMOUNT, Y = SOURCE_AMOUNT, Z = 1
void main() {
    uint point_idx = gl_GlobalInvocationID.x;
    uint source_idx = gl_GlobalInvocationID.y;

    if (point_idx >= POINT_AMOUNT || source_idx >= SOURCE_AMOUNT)
        return;

    Output point = outputs[source_idx * POINT_AMOUNT + point_idx];

    if (!point.found_source) {
        neighbours[source_idx * POINT_AMOUNT + point_idx] = -1;
        return;
    }

    // Find the closest centroid
    // todo: this could be modified in such a way as to cluster similar distances in general,
    //       and not just similar origins
    float dist = distance(centroids[source_idx * SOURCE_AMOUNT + 0], point.location);
    uint centroid_ = 0;
    for (int i = 1; i < KMEANS_CENTROIDS; i++) {
        float new_dist = distance(centroids[source_idx * SOURCE_AMOUNT + i], point.location);
        if (new_dist < dist) {
            dist = new_dist;
            centroid_ = i;
        }
    }

    // Store the found neighbouring centroid
    neighbours[source_idx * POINT_AMOUNT + point_idx] = int(centroid_);
}
