#version 460
#include "imports/utils.comp"

const uint SOURCE_AMOUNT = 1;

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly restrict buffer SourceLocations {
    vec3 sources[];
};

layout(std430, binding = 1) writeonly restrict buffer AudioInstances {
    Instance instances[];
};

void main() {
    uint source_idx = gl_GlobalInvocationID.x;
    if (source_idx >= SOURCE_AMOUNT)
        return;

    vec3 source = sources[source_idx];

    instances[source_idx].position = source;
    instances[source_idx].additional_dist = 0;
    instances[source_idx].attenuation = 1.0;
    instances[source_idx].index = source_idx;
}