[package]
name = "audio-processor"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = "0.38.0"
crevice = "0.18.0"  # for automatic GLSL struct-padding
plotters = "0.3.7"
rand = "0.9.1"
sofar = "0.2.1"
vk-mem = "0.4.0"

[profile.dev]
opt-level = 0
